name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up PHP with extensions
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mbstring, pdo, sqlite3, openssl

    - name: Validate PHP Version
      run: php -v

    - name: Update Composer
      run: composer self-update

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: composer install --prefer-dist
      env:
        COMPOSER_MEMORY_LIMIT: -1

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Set Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Prepare SQLite Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Run Tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test
